import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { i18n, Locale } from "../../../i18n.config";

import { getDictionary } from "./dictionary";
import Header from "./_components/header";
const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const dictionary = await getDictionary(lang);

  return (
    <html lang={lang} dir={lang === "fa" ? "rtl" : "ltr"}>
      <body className={inter.className}>
        <Header dictionary={dictionary} />
        <div className="px-8">{children}</div>
      </body>
    </html>
  );
}
